"""
Door 2 reproduces the gravel-river test set (GRLP's steady states).

The golden reference (``reference.npz``, generated by ``generate_reference.py`` from
stable GRLP) is the authority; the self-contained finite-volume transport-limited
rule -- run through the explicit-rule hook -- must reproduce it. Two checks:

  1. *Fixed point* (all topologies, instant): evaluated at GRLP's steady state, the
     rule's rate is machine-zero -- the two solvers share the same steady-state
     *shape*. Note this alone does NOT constrain ``k_Qs``: the steady-state slope is
     ``(Q_head*S0**(7/6)/Q)**(6/7)``, in which ``k_Qs`` cancels (it sets the
     relaxation timescale, not the profile).
  2. *Magnitude* (all topologies, instant): sediment discharge at the golden profile
     equals GRLP's -- this is what pins ``k_Qs`` and the flux formula (a wrong
     ``k_Qs`` passes check 1 but fails here).
  3. *Cold start* (representative topologies): from a flat bed, explicit stepping
     relaxes to GRLP's steady state.

This test needs **no GRLP** -- the golden is saved and the rule is pure substrate
physics -- which is the point: door 2 reproduces GRLP without depending on it.
"""

import os

import numpy as np
import pytest

from topologies import SPECS, widths, S0, Z_BL
from fluvtree.processes import build_network, Rule, TransportLimitedRate

_REF = np.load(os.path.join(os.path.dirname(__file__), "reference.npz"))


def _golden_segments(name):
    z = _REF["%s__z" % name]
    lengths = _REF["%s__lengths" % name]
    return np.split(z, np.cumsum(lengths)[:-1])


def _fluvtree_network(spec, z_init):
    return build_network(
        spec["up"], spec["down"], spec["x"], z_init, spec["Q"],
        widths(spec), S0, spec["x_bl"], Z_BL)


@pytest.mark.parametrize("name", list(SPECS))
def test_grlp_steady_state_is_fixed_point(name):
    """At GRLP's steady state the door-2 rule's rate is machine-zero."""
    spec = SPECS[name]
    golden = _golden_segments(name)
    rn = _fluvtree_network(spec, [g.copy() for g in golden])
    rates = TransportLimitedRate()(rn, 1.0)
    max_dz_dt = max(np.max(np.abs(rates[s])) for s in rn.segment_ids)
    assert max_dz_dt < 1e-15   # m/s; measured ~1e-22


@pytest.mark.parametrize("name", list(SPECS))
def test_during_flood_Qs_matches_golden(name):
    """Sediment discharge at the golden profile matches GRLP's (conserved)."""
    spec = SPECS[name]
    golden = _golden_segments(name)
    rn = _fluvtree_network(spec, [g.copy() for g in golden])
    rate = TransportLimitedRate()
    qs = []
    for s in rn.segment_ids:
        z = rn.get_segment_field(s, "z")
        x = rn.get_segment_field(s, "x")
        Q = rn.get_segment_field(s, "Q")
        S = np.abs(np.diff(z) / np.diff(x))
        qs.append(rate.k_Qs * 0.5 * (Q[:-1] + Q[1:]) * S ** (7 / 6.0))
    assert np.allclose(np.hstack(qs), _REF["%s__qs" % name], rtol=0, atol=1e-9)


@pytest.mark.parametrize("name", ["single_segment", "symmetric_confluence"])
def test_cold_start_relaxes_to_grlp(name):
    """From a flat bed, explicit stepping relaxes to GRLP's steady state."""
    spec = SPECS[name]
    golden = _golden_segments(name)
    rn = _fluvtree_network(spec, [np.zeros(len(xi)) for xi in spec["x"]])
    rule = Rule(rn, TransportLimitedRate())
    for _ in range(120000):
        rule.step(1.0e7)
    for s in rn.segment_ids:
        assert np.allclose(rn.get_segment_field(s, "z"), golden[s],
                           rtol=0, atol=2e-3)
